name: run-tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: yarn

      - name: Lint files
        run: yarn lint

      # Disabled as currently there are no tests
      # - name: Run tests
      #   run: yarn test 
      # Test that build works
      - name: Build production bundle
        run: yarn build